/** @type {import("./types.js").RawShoeOrderResponse} */
export const mockShoeOrderData = {
  success: true,
  message: "Success",
  data: {
    orderDetails: {
      salesPerson: "",
      physician: "LEOR SKOCZYLAS",
      fitterInArea: "Sandra Costlow",
      alternateFitter: "JARED BEDICK / By Road7.64 Miles",
      fittingAppointmentDate: "2026-02-16T09:00:00",
      dispensingAppointment: null,
      priorAuth: "Auth Started",
      doFollowUp: "Resent D.O.-2026-04-10",
      patientFollowUp: "Mailed DO-2026-04-10",
      doDetails: {
        product: "Diabetic Shoes",
        dateDispensed: null,
        insertType: "A5514 - Custom Molded Inserts- CAD-CAM",
        toeFiller: "No Filler",
        diagnosis1: "",
        rxSignatureDate: "2026-01-29T00:00:00",
        rxExpirationDate: "2026-07-29T00:00:00",
        cmnSignatureDate: "2026-01-30T00:00:00",
        cmnExpirationDate: "2026-04-30T00:00:00",
        accommodations: "",
      },
      shoeDetails: {
        request: 810176,
        barCode: "190446890195",
        manufacturer: "DR COMFORT",
        dealer: "DR. COMFORT",
        gender: "Male",
        style: "52180",
        colour: "GREY",
        size: "13",
        width: "WIDE (E/EE)",
        closureType: "Elastic Lace",
        arrivalDate: "2026-04-10T06:51:35",
        insoles: "Custom Molded",
        description: "Finch Grey Elastic Lace",
        secondChoice: "Manufacturer: DR COMFORT-Style:52050-Color:BLUE-ClosureType: Elastic Lace-Size:13-Width:WIDE (E/EE)",
      },
      txnHistory: [
        {
          date: "01/28/2026",
          time: "10:10:11 AM",
          status: "CREATED D.O.",
          createdBy: "MARKETTA WILSON",
          misc: "",
        },
        {
          date: "01/28/2026",
          time: "10:30:38 AM",
          status: "FAX IN QUE TO SEND",
          createdBy: "MARKETTA WILSON",
          misc: "Sending",
        },
        {
          date: "01/30/2026",
          time: "9:11:25 AM",
          status: "INCOMPLETE D.O",
          createdBy: "JOHNNA DURBIN",
          misc: "Needs to complete Steps 1-3 on CMN.",
        },
        {
          date: "01/30/2026",
          time: "11:17:46 AM",
          status: "CREATED D.O Incomplete",
          createdBy: "MAGALYS PEREZ",
          misc: "",
        },
        {
          date: "02/03/2026",
          time: "2:44:15 PM",
          status: "USEABLE",
          createdBy: "ELSIE SANTIAGO",
          misc: "",
        },
        {
          date: "02/03/2026",
          time: "2:44:15 PM",
          status: "INCOMPLETE D.O MARKED AS COMPLETED",
          createdBy: "ELSIE SANTIAGO",
          misc: "",
        },
        {
          date: "02/03/2026",
          time: "2:44:15 PM",
          status: "D.O. FILLED",
          createdBy: "ELSIE SANTIAGO",
          misc: "",
        },
        {
          date: "02/04/2026",
          time: "7:55:50 AM",
          status: "SHOE FITTER ASSIGNED",
          createdBy: "Sandra Costlow",
          misc: "null Fitter :Sandra Costlow",
        },
        {
          date: "02/16/2026",
          time: "11:03:17 AM",
          status: "FITTER DOCUMENT SIGNED",
          createdBy: "MARCELO PINHEIRO",
          misc: "<a target='_blank' href='../Handlers/fileDownloadHandler.ashx?filePath=D:\\MYDMEDeployment\\Files\\custom_inpersonForm\\668981_349253.pdf'>Document</a>",
        },
        {
          date: "04/10/2026",
          time: "9:30:23 AM",
          status: "CREATED REVISE D.O",
          createdBy: "MARC VETRANO",
          misc: "test , Reason: Expired DO <a href='/DME/ReviseDOFormPdf?personId=668981&categoryNo=1&yhpId=0&productId=1&doId=349253'>View Revise DO</a>",
        },
        {
          date: "02/16/2026",
          time: "1:54:46 PM",
          status: "REQUESTED",
          createdBy: "Sandra Costlow",
          misc: "PoNo # 429548 ",
        },
        {
          date: "02/16/2026",
          time: "1:54:46 PM",
          status: "3D SCANNED LINKED TO ORDER",
          createdBy: "Sandra Costlow",
          misc: "<a href='/PatientManagement/DownloadUploadedDocument?fileName=D:\\MyDmeDeployment\\Files\\uploads3d\\219093_Marc_Brawer.zip'>View Scans</a> <a href='/PatientManagement/DownloadUploadedDocument?fileName=D:\\MYDMEDeployment\\Files\\3DScan_219093_MARC_BRAWER_349253.pdf'>Order Form</a>",
        },
        {
          date: "02/16/2026",
          time: "1:54:46 PM",
          status: "ORDERED",
          createdBy: "Sandra Costlow",
          misc: "",
        },
        {
          date: "02/19/2026",
          time: "1:32:07 PM",
          status: "ORDER CONFIRMED BY MANUFACTURER",
          createdBy: "WILLIAM VANEGAS",
          misc: "15161438",
        },
        {
          date: "04/10/2026",
          time: "6:51:35 AM",
          status: "RESERVED",
          createdBy: "Sandra Costlow",
          misc: "<a href='/TestingSupplies/TSPOD?personId=SO1oz9a7gMw=&doId=349253&categoryNo=1&requestId=810176' target='_blank'>View POD</a>",
        },
      ],
    },
  },
  statusCode: 200,
};
