/** @type {import("./types.js").RawCgmOrderResponse} */
export const mockCgmOrderData = {
  success: true,
  message: "Success",
  data: {
    orderDetails: {
      product: "CGM",
      salesPerson: "JOE REYES",
      cgmEducator: "Sandra Costlow",
      patientAdvocate: "AMERICA KILLINGBECK",
      physician: "JENNIFER SNELL",
      dateConfirmed: null,
      appointmentDate: "2026-04-15T00:00:00",
      doFollowUp: "Resent D.O.-2026-04-14",
      patientFollowUp: "Advised PT to Follow-2026-04-14",
      priorAuth: "Auth Not Required",
      doDetails: {
        diagnosis1: "E11.65 Type 2 diabetes mellitus with hyperglycemia",
        diagnosis2: "",
        cgmBilling: "Commercial",
        cgmModel: "Dexcom G7",
        shipToAddress: "3324 GLADYS ST,,JACKSONVILLE,FL,32209",
        validAddress: "No",
        overrideUSPS: "No",
        status: "Active",
        snfHospice: "No",
        shipmentDuration: "1 Month",
        paymentType: "",
        openInvoices: "",
        totalAmount: "",
        paymentNotes: "",
        isReorderCancelled: "No",
        thinFilmStrips: "Yes-14/04/2026",
        effectiveDate: "2026-04-01T00:00:00",
        expirationDate: "2026-03-31T18:38:25",
        autoClaimCreation: "No",
      },
      requestDetails: {
        request: 811914,
        isAnchorOrder: false,
        authorization: "",
        units: "",
        authDates: "",
        shipDate: "2026-03-31T18:38:25",
        shippedTo: null,
        cgmModel: "Dexcom G7",
        cgmType: "Commercial",
        shipmentDuration: "1 Month",
        itemDetails: [
          {
            item: "Receiver",
            quantity: 1,
            serialNumber: "",
            lastShipmentDate: "2026-03-31T18:32:40",
            futureShipDate: "2031-03-31T18:32:40",
          },
          {
            item: "Sensor",
            quantity: 3,
            serialNumber: "",
            lastShipmentDate: "2026-03-31T18:32:40",
            futureShipDate: "2026-04-30T18:32:40",
          },
          {
            item: "Thin Film Strips",
            quantity: 1,
            serialNumber: "",
            lastShipmentDate: "2026-03-31T18:32:40",
            futureShipDate: "2026-05-01T00:00:00",
          },
        ],
      },
      txnHistory: [
        {
          date: "03/31/2026",
          time: "6:21:55 PM",
          status: "CREATED D.O.",
          createdBy: "MARC VETRANO",
          misc: "",
        },
        {
          date: "03/31/2026",
          time: "6:21:55 PM",
          status: "FAX IN QUE TO SEND",
          createdBy: "MARC VETRANO",
          misc: "DO Set to Fax",
        },
        {
          date: "03/31/2026",
          time: "6:29:30 PM",
          status: "D.O. FILLED",
          createdBy: "MARC VETRANO",
          misc: "",
        },
        {
          date: "03/31/2026",
          time: "6:29:30 PM",
          status: "RESERVED",
          createdBy: "MARC VETRANO",
          misc: "",
        },
        {
          date: "03/31/2026",
          time: "6:29:30 PM",
          status: "PENDING AUTHORIZATION",
          createdBy: "MARC VETRANO",
          misc: "",
        },
        {
          date: "03/31/2026",
          time: "6:31:16 PM",
          status: "AUTH NOT REQUIRED",
          createdBy: "MARC VETRANO",
          misc: "",
        },
        {
          date: "03/31/2026",
          time: "6:32:40 PM",
          status: "INSURANCE VERIFIED",
          createdBy: "MARC VETRANO",
          misc: "",
        },
        {
          date: "03/31/2026",
          time: "6:38:25 PM",
          status: "PRODUCT DISPENSED",
          createdBy: "MARC VETRANO",
          misc: "",
        },
      ],
    },
  },
  statusCode: 200,
};
